### ISSUE TITLE
Prefix Problem

### ISSUE THREAD

**Issue by masterhacka** [DomeDD/BetterNick#102]
Wie hier bereits geschrieben: https://github.com/DomeDD/BetterNick/issues/95
habe ich immer noch ein Problem mit dem Prefix. Habe die entsprechenden Einträge aus der config genommen. Der Suffix klappt nun ohne Probleme. Beim Prefix jedoch hat nun der genickte Spieler gar keinen Prefix, obwohl er standardmäßig den Prefix Spieler haben sollte. Wenn ich den Prefix in der Config stehen lasse, wird beim unnick der Spieler Prefix nicht gelöscht -> in LuckyPerms hat der jeweilige Spieler nun eine Permission (100) dafür, diese überschreibt dann logischerweise die Prefixe der Gruppen. Ich hoffe du hast eine Lösung dafür.

**Comment by DomeDD** [comment]
Adde mich mal bitte auf Skype: live:dominik.diller_1

**Comment by masterhacka** [comment]
Hab ich gemacht
