### ISSUE TITLE
Nick not changing

### ISSUE THREAD

**Issue by theasern** [DomeDD/BetterNick#103]
So, basically /skin works fine but the /nick command sends this error. and it clears my name (
![imagen](https://user-images.githubusercontent.com/16941905/41043393-22ff5db0-69a4-11e8-9165-8f5b48c8cc65.png )

>  10:21:39 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.scanPlain(ScannerImpl.java:2027) ~[spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.scanPlainSpaces(ScannerImpl.java:2046) ~[spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at org.yaml.snakeyaml.reader.StreamReader.prefixForward(StreamReader.java:209) ~[spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO Caused by: java.lang.StackOverflowError 06.06 10:21:39 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151] 06.06 10:21:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424) [EssentialsX-2.0.1.jar:?] 06.06 10:21:39 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:435) [EssentialsX-2.0.1.jar:?] 06.06 10:21:39 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at de.domedd.betternick.commands.NickCommand.onCommand(NickCommand.java:40) [BetterNick%201.8.3%20-%201.12.2.jar:?] 06.06 10:21:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-BT71-1.12.2.jar:git-Spigot-c3093ef-aa25568] 06.06 10:21:39 [Server] INFO org.bukkit.event.EventException: null 06.06 10:21:39 [Server] ERROR Could not pass event PlayerCallRandomNickEvent to BetterNick v6.9

**Comment by DomeDD** [comment]
Did you enable Essentials Nick?

**Comment by theasern** [comment]
Yes, I have essentials nick enabled

**Comment by DomeDD** [comment]
This error should be fixed in v7.0
Otherwise open a new ticket please :)
