### ISSUE TITLE
Chunk not loading and names chaning to an blank and takes around 2-4 seconds to load.

### ISSUE THREAD

**Issue by Dream-cake** [DomeDD/BetterNick#106]
1. sometimes when do /nick it does not reload the chunks
2. it does not show a name and a name in tab https://imgur.com/a/ySNKqSM
3. it takes around 6 seconds to load

if you want to contact me here is my discord "SpooderCraft | Dream-MC#3911"

**Comment by Dream-cake** [comment]
log

https://pastebin.com/D1Qmc3HZ

**Comment by DomeDD** [comment]
2 and 3 will be fixed in the next update (v7.0). Still working on a chunk reload fix!
