### ISSUE TITLE
No Nametag

### ISSUE THREAD

**Issue by Pastsicc** [DomeDD/BetterNick#109]
Anytime I nick myself using a specific name (not doing autonick or nick with no name after)
This happens. Please help.
![unknown 2](https://user-images.githubusercontent.com/40550242/41825013-afbfb492-77e7-11e8-91f4-2ed36744aad1.png)

**Comment by DomeDD** [comment]
With the newest version (v7.0) this is fixed!

**Comment by theasern** [comment]
I keep getting the same problem although I have version 7.0 installed

**Comment by Pastsicc** [comment]
Same here.

**Comment by DomeDD** [comment]
Do you have any othe nametag editing plugins installed? Cause on my server everything is working fine when I type in '/nick testname'

**Comment by darkknight20002** [comment]
same error here

**Comment by theasern** [comment]
Does essential conflict?

**Comment by Mattybootsy** [comment]
> Do you have any other nametag editing plugins installed? Cause on my server everything is working fine when I type in '/nick testname'

I have the same problem. The only other plugin that could effect it is Essentials
![screen shot 2019-01-02 at 8 36 33 pm](https://user-images.githubusercontent.com/37625624/50620579-1e8b2c80-0ece-11e9-8260-552c9d9f71d3.png)
