### ISSUE TITLE
Players don't have a name on console/server menu while nicked

### ISSUE THREAD

**Issue by Gilbat** [DomeDD/BetterNick#110]
![capture](https://user-images.githubusercontent.com/31635433/41996314-1a665826-7a1a-11e8-9a20-267f5f7f1288.PNG)
![capture](https://user-images.githubusercontent.com/31635433/41996368-4389a636-7a1a-11e8-831a-20857080c779.PNG)
After nicking, the player has no name on the console while using commands, and on the server menu.

**Comment by DomeDD** [comment]
Do you have any other nametag editing plugins installed? Cause on my server everything is working fine when I type in '/nick testname'

**Comment by Gilbat** [comment]
Nope, all I had installed at the time was BetterNick and Luckperms, I'll try again though without luckperms to see if that does anything.
