### ISSUE TITLE
Make It Interact with LuckPerms

### ISSUE THREAD

**Issue by eric2788** [DomeDD/BetterNick#114]
I have changed the displayname prefix and the chat prefix but the chat display still showing my real prefix because of luckperms.
so i hope it can hook with luckperms
luckperms plugin: https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/

**Comment by DomeDD** [comment]
Sorry for the late answer, it is working with LuckPerms, at least on my server...
