### ISSUE TITLE
CloudNet Chat/Prefix

### ISSUE THREAD

**Issue by ConnorSte** [DomeDD/BetterNick#116]
Hey,
I have a problem with the nickname prefix and chat.
I use the following two plugins: cloudnet-tools-chat-2.1.10, cloudnet-tools-simplenametags-2.1.10.
If I rename myself it looks like this: http://prntscr.com/kpo9gt

**Comment by DisneyChannelTV** [comment]
Bei mir genau so

**Comment by DomeDD** [comment]
Double post: https://github.com/DomeDD/BetterNick/issues/131
