### ISSUE TITLE
2 Buggs

### ISSUE THREAD

**Issue by DekoLP** [DomeDD/BetterNick#12]
Hey,

ich habe hier 2 Buggs/Fehler:
1. Fehler: https://hastebin.com/qawoqecera.vbs
2. Bug: [Tritt nicht immer auf. Tritt zufällig auf] Wenn ich /unnick eingebe wird nur mein Skin resettet. KEIN FEHLER
https://hastebin.com/imipagifuj.vbs

**Comment by DekoLP** [comment]
Achja, am meisten passiert es wenn ich mit AutoNick genickt werde

**Comment by DekoLP** [comment]
Also der Bug

**Comment by DomeDD** [comment]
Ich werde gleich ein Update hochladen, was das eventuell fixt. Ich erkenne keinen Fehler in meinem Code, also wird es sehr wahrscheinlich an der Verbindung von deinem Server zu deiner MySQL Datenbank liegen.
