### ISSUE TITLE
CloudNet 

### ISSUE THREAD

**Issue by Spark61** [DomeDD/BetterNick#124]
Hallo,
können sie das Plugin mit der Cloud [CloudNet](https://www.spigotmc.org/resources/cloudnet-the-cloud-network-environment-technology.42059/) kompatibel machen, weil es da einige Probleme gibt und deswegen zum Beispiel der Spieler Name nicht über den Kopf angezeigt wird.

LG Spark61

-----Update-----
das Plugin ist doch schon mit CloudNet kompatibel, aber mein Prefix von CloudNet bleibt da und mein Nick ist weg

**Comment by Spark61** [comment]
Sie können sich ja die Cloud downloaden ist ja free oder Mal auf den CloudNet discord fragen ob der Code so funktionieren würde

**Comment by Spark61** [comment]
Ich kann mir morgen auch gerne Mal das Plugin anschauen. Vllt finde ich ja den Fehler

**Comment by Spark61** [comment]
Ups habe es ausversehen geschlossen

**Comment by Spark61** [comment]
Also habe ich das jetzt richtig gesehen das es eigentlich mit CloudNet compatibel sein sollte? In welcher Klasse wird das mit den setzten von den Namen gemacht für CloudNet? Dann kann ich es mir Mal anschauen und dir vllt den Fehler sagen

**Comment by Spark61** [comment]
Und wie änderst du den Namen von den Spieler bzw den Rang

**Comment by Spark61** [comment]
Und wie änderst du den Displayname habe jetzt keine jetzt um es nachzuschauen

**Comment by Spark61** [comment]
Mit 
CloudPlayer cp = CloudAPI.getInstance().getOnlinePlayer(player.getUniqueId());
CloudAPI.getInstance().updatePlayer(cp);
updatest du nur den Spieler die Cloud geht aber über den Namen und nicht den DisplayName oder den CustomName. Um den Fehler zu fixen musst du ein eigenes PlayerList Plugin schreiben und an die Cloud den Genickten namen weiter geben.

**Comment by Spark61** [comment]
Hier gebe ich dir auch mal einen Link für den CloudNet Discord da können sie es dir warscheinlich besser erklären als ich es könnte. https://discord.gg/wKBweAW

**Comment by DomeDD** [comment]
Danke, ich ändere den Namen des Spielers, nicht den DisplayName oder CustomName

**Comment by DomeDD** [comment]
Double post: https://github.com/DomeDD/BetterNick/issues/131
