### ISSUE TITLE
Prefix will reset after a Player join

### ISSUE THREAD

**Issue by CookiePlaysTV** [DomeDD/BetterNick#13]

**Comment by DomeDD** [comment]
Etwas genauer bitte. Darunter, was du mir da geschrieben hast, kann ich mir nicht viel vorstellen.

**Comment by CookiePlaysTV** [comment]
Also nachdem ein Spieler joint wird ja die Tablist upgedatet und dann wird der echte Prefix angezeigt und nicht der Nick Prefix!

**Comment by CookiePlaysTV** [comment]
https://prnt.sc/fv8xy2

statt prefix nur &7

**Comment by CookiePlaysTV** [comment]
Und nach einem Unnick musst du die Tab updaten damit der echte nick angezeigt wird!

**Comment by DomeDD** [comment]
Hast du noch irgendein Tablist Prefix plugin installiert?

**Comment by CookiePlaysTV** [comment]
E
