### ISSUE TITLE
[CloudNet] Name wird nicht angezeigt

### ISSUE THREAD

**Issue by Spark61** [DomeDD/BetterNick#131]
Hallo,
ich habe ein Problem. Ich benutzte CloudNet und wenn ich mich nicke kommt dieser Error in der Console. https://haste.dsyn.ga/ewegerokar.cs
Es ändert sich nur mein Skin und mein Name bleibt normal. Wäre cool wenn sie mir helfen können bei den letzten malen war es ja leider nicht so.

LG Spark61

**Comment by Spark61** [comment]
gut diese Fehler kamen glaube ich weil die Datenbank Verbindung nicht da war. Aber ich habe das Plugin jetzt mal auf meinen Spigot 1.12 Server ausprobiert wo nur Worldedit drauf ist. Und da geht es auch nicht komplett. Probiere es gleich auf der Cloud noch mal aus. 
Hier mal ein Screenshot BloomGames ist der genickte und nur so die tablist ist eigentlich normal buggt aber manchmal in mc rum beim schnellen serverwechsel 
![image](https://user-images.githubusercontent.com/28624736/50353801-a590ea00-0549-11e9-9a2d-848f88eb7503.png)

**Comment by Spark61** [comment]
So ich habe jetzt auf der Cloud das mit den Prefix eingestellt da sieht es jetzt so aus. Also es geht auch da nicht... aber jetzt kommen keine Errors mehr
![image](https://user-images.githubusercontent.com/28624736/50353990-4b445900-054a-11e9-8011-a9b8f8ef374a.png)

**Comment by Spark61** [comment]
außerdem wird auf der Cloud der Name auch nicht angezeigt Nur Owner | also genauso wie beim Nametag

**Comment by Spark61** [comment]
Und @DomeDD es wäre cool wenn ich dich auf z.b. Discord Skype anschreiben könnte und ich dir da das Problem genau erkläre, weil da kannst du direkt zurückschreiben

**Comment by DomeDD** [comment]
Update ist draußen, wäre super wenn du mir sagen kannst, ob es funktioniert.
Update is out, would be great if you can tell me if it's working

**Comment by Spark61** [comment]
Werde ich nachher Mal versuchen

**Comment by Spark61** [comment]
![image](https://user-images.githubusercontent.com/28624736/51187793-e37cf600-18dc-11e9-9e11-0b9d1a498f38.png)
![image](https://user-images.githubusercontent.com/28624736/51187810-eed02180-18dc-11e9-9b91-24b7ecc30419.png)
Beides sollte eigentlich nicht so sein

**Comment by Spark61** [comment]
wegen den namen dort musst du einfach die uuid von den spieler ändern zu der von den genickten namen

**Comment by Spark61** [comment]
aber mir ist dass eigentlich gerade mit betternick egal habe mir jetzt einfach selbst eins gecodet
