### ISSUE TITLE
Chunks unload when nicked

### ISSUE THREAD

**Issue by UnlimitedNinjas** [DomeDD/BetterNick#134]
MC Version: 1.12.2
Java: 8
plugin version: 7.2
---------------------------------
When doing /nick it unloads chunks and everything is invisible, reloading the chunks with F3 + A fixes it.

**Comment by DomeDD** [comment]
I know that Bug, it got fixed in the 1.13.X with the minecraft update. I don't exactly know why it happens in 1.12 and there is no way to fix that, sorry :C
