### ISSUE TITLE
Mysql / cloudnet fehler

### ISSUE THREAD

**Issue by drummerschlumpf** [DomeDD/BetterNick#136]
Hallo, Ich habe das Problem, dass wenn Ich mich Nicke bekomme Ich einen anderen Skin aber es wird überhaupt kein name angezeigt (also im chat steht nur ": nachricht")
wenn ich allerdings mysql deaktiviere funktioniert es einwandfrei

**Comment by DomeDD** [comment]
Ich arbeite an einem CluodNet update

**Comment by DomeDD** [comment]
Double post: https://github.com/DomeDD/BetterNick/issues/131
