### ISSUE TITLE
Better Nick Suport für bugeechat und Bugeetablist ++

### ISSUE THREAD

**Issue by rexwin2001** [DomeDD/BetterNick#14]
Könntest du es auch machen das man bugeechat und bugeetablist ++ mit Better Nick Supportet wird?? Vielen Dank noch mal

**Comment by nuttah** [comment]
+1

**Comment by BrainStone** [comment]
There are two ways of doing that for BungeeChat.

Either set the display name of the player to the nick, or add a placeholder. I'll provide help with that if youu need any. (I speak German too)

**Comment by DomeDD** [comment]
Ich werde mich nach meinem Urlaub daran machen.

**Comment by DomeDD** [comment]
"Either set the display name of the player to the nick" dem Spieler wird der Displayname gesetzt.

**Comment by BrainStone** [comment]
Ok. Dann ist es mit Bungee Chat compatibel

**Comment by nuttah** [comment]
Hello. What has changed.. Bot Bungeechat as well as BungeetablistPlus is ignoring the nicked usernames.
Have you implemented the features ?
