### ISSUE TITLE
Colors in NameTag not working

### ISSUE THREAD

**Issue by zwamdurkel** [DomeDD/BetterNick#140]
![image](https://user-images.githubusercontent.com/13705380/54490255-973a3c00-48b4-11e9-8dd8-5c74b5f7389f.png)
as you can see the color codes are not being applied to the nametag 
command used: /nick &6test

list of plugins:
![image](https://user-images.githubusercontent.com/13705380/54490279-c3ee5380-48b4-11e9-825f-beeb528d28f5.png)

**Comment by DomeDD** [comment]
You can't nick yourself with '/nick **&**6test'
Use the config to setup a colored prefix
