### ISSUE TITLE
problem  fake nick more servers

### ISSUE THREAD

**Issue by ProDash1998** [DomeDD/BetterNick#15]
When from X server with a false nick idea on Server Z then I have a real nick. Both serfs are supported under mysql

using Waterfall-131.jar
https://youtu.be/N_3yPd6E9J0

Server version 1.12

**Comment by DomeDD** [comment]
Seems like Auto Nick is not activated!

**Comment by ProDash1998** [comment]
Auto Nick is activated

**Comment by DomeDD** [comment]
hmm...

**Comment by DomeDD** [comment]
Ok, do I understand you right? You are on Server X. And you are nicked. Then you join an other server and you don't have a nick?
Quick Fixes: Make sure that you enabled Auto Nick for your client (/autonick or using AutoNick tool on lobby server) and make sure that 'Config.BungeeCord Lobby Mode' in your config.yml is **false**

**Comment by ProDash1998** [comment]
yes i have online_mode: false because plugins BPA Must have included on false because premium will not be available

**Comment by ProDash1998** [comment]
And no change nick in Tablist

**Comment by DomeDD** [comment]
"yes i have online_mode: false" -> that is not important for my plugin
