### ISSUE TITLE
Change skin for player when nicked

### ISSUE THREAD

**Issue by DaLimaBean** [DomeDD/BetterNick#17]
Maybe you could add the ability to see your own skin when nicked instead of seeing your default one.
A few other plugins have done it so it shouldn't be so hard.

**Comment by DomeDD** [comment]
To do that I have to kill the player and respawn him. But in Minigames that would be bad.
But I will add an option do enable/disable Skin Self Update

**Comment by DomeDD** [comment]
Added: https://www.spigotmc.org/resources/better-nick-api-1-8-3-1-12.39633/update?update=181388
