### ISSUE TITLE
Bungeecord Support Klappt nicht.

### ISSUE THREAD

**Issue by ZockerBoysHD** [DomeDD/BetterNick#20]
Ich habe Das Plugin auf Meiner Lobby& Unter serevr jeweils mit MYSQl verbunden. Werde ich aber genickt, und wechsle den server, passiert nichts. Also der nick ist wie der Echt nick. Obwohl ich genickt binb.

**Comment by DomeDD** [comment]
Du bekommst jedes mal einen neuen Nick, wenn du einem neuen Server joinst und AutoNick aktiv hast.
