### ISSUE TITLE
Support for CTSNC custom prefixes or permission remove on /nick

### ISSUE THREAD

**Issue by SweetSofiMC** [DomeDD/BetterNick#21]
When I do /nick i have two prefixes in my nametag, [ADM] and [VIP] (as in the config file). So can you do a configurable permission remove on /nick or an command execution for the perms plugin to do so, please?

**Comment by DomeDD** [comment]
Send me a link to you config.yml please

**Comment by DomeDD** [comment]
In the CTSNC API I couldn't find any methods to set a prefix. I'm working on a custom version of BetterNick to set the player in a new permissions group

**Comment by SweetSofiMC** [comment]
Oh, good, if you finish that version please let me know, thank you
