### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by PaXo0** [DomeDD/BetterNick#22]
Hello i have been looking for a decent nickname plugin ( like this one ) and i have noticed when you do /nick and when you switch server the name/skin either resets off and you haft to re /nick or the auto nick option i was wondering if you can add an option if you are nicked in a set server ( though MySQL ) the nickname and skin would carry over and you would keep the name and skin until you /unnick

**Comment by DomeDD** [comment]
Will be added!

**Comment by PaXo0** [comment]
Thanks!

**Comment by DomeDD** [comment]
I'm sorry but at the moment I can't add this. There are other feature requests and bug reports which are more important than this here. Sorry for that!
