### ISSUE TITLE
Modern BedWars using BetterNick

### ISSUE THREAD

**Issue by DekoLP** [DomeDD/BetterNick#25]
Hey,

Könntest du bitte dieses Plugin zu den ,,Plugins using this API:" hinzufügen? 

Link: https://www.spigotmc.org/resources/✖-modern-bedwars-like-german-server-1-8-1-9-1-10-1-11-new-top-5-heads-✖.38619/

LG
DekoLP

**Comment by DomeDD** [comment]
Das Plugin resettet nur den Nicknamen nach der Runde. Mehr nicht. Also nein
