### ISSUE TITLE
Unnicking wont work

### ISSUE THREAD

**Issue by SoulWolfX** [DomeDD/BetterNick#27]
Ok i tried this plugin on my server but when i decided to un nick it made an error and didnt work so i tried renicking then it just broke the plugin pretty much also the gui doesnt work.

**Comment by DomeDD** [comment]
So if you say you get an error, why you don't send it to me? I can't do anything without that error!
And could you tell me your Java and Minecraft version you are using?

**Comment by SoulWolfX** [comment]
Ok I have java 8 and ive tried both 1.7.10 and 1.8.9 cuz my server when i first got the plugin supported 1.8.9 - 1.12.1 and now it supports 1.7.10 - 1.12.1 my error is  
![2017-09-12_18 34 57](https://user-images.githubusercontent.com/30161396/30351393-21999eb4-97e9-11e7-9bac-13ebc307a24c.png)
for client side and on the console its https://pastebin.com/sGSgnEJE sorry for the late response btw

**Comment by DomeDD** [comment]
The error says access denied to you mysql database.
1.7.10 is also not supported btw

**Comment by DomeDD** [comment]
Re check your mysql connection datas and make sure you are running supported minecraft versions!
