### ISSUE TITLE
Nick prefix not working

### ISSUE THREAD

**Issue by LoYungSum** [DomeDD/BetterNick#28]
After play does /nick, the prefix will still be there and it will not change. 

Here is the Config of betternick:
Config:
    Auto Update Check: true
    Auto Update Download: true
    MySQL: true
    API Mode: false
    # If true, you won't get a nickname on join (if the client enabled AutoJoin and has the Permissions)
    BungeeCord Lobby Mode: true
    Use Vault: true
    # Nick Name Prefix for chat messages; I recommend to leave Display Name Prefix empty
    Display Name Prefix: ''
    # Nick Name Prefix for nametag; I recommend to leave Name Tag Prefix empty
    Name Tag Prefix: ''
    # Nick Name Prefix for tablist
    Tablist Name Prefix: ''
    # Overwrites the Player Prefix, on unnick the Player will get his old Prefix
    Permissions System Prefix: ''
    # Be aware of that the Client gets killed and respawned when Skin Self Update is true
    Skin Self Update: false
    Nicked Actionbar: true
    Messages:
        Enabled: true
        Nick Name Set: '&8[&e&lPots &b&lNetwork&8] &7Your nickname is &5[NAME]&7.'
        Nick Name Removed: '&8[&e&lPots &b&lNetwork&8] &7Your nickname has been removed.'
        Nick Set Error: '&8[&e&lPots &b&lNetwork&8] &7Your name could not be changed.'
        Skin Set: '&8[&e&lPots &b&lNetwork&8] &7You have a new skin now.'
        Skin Removed: '&8[&e&lPots &b&lNetwork&8] &7Your skin has been removed.'
        Skin Set Error: '&8[&e&lPots &b&lNetwork&8] &7Your skin could not be changed.'
        See Real Name: '&8[&e&lPots &b&lNetwork&8] &7The real name of &3[PLAYER] &7is &e[NAME]&7.'
        See Real Name Error: '&8[&e&lPots &b&lNetwork&8] &7This Player is not online!'
        Get Nicked Players Header: '&8[&e&lPots &b&lNetwork&8] &7Listing all nicked players and their real names...'
        Get Nicked Players: '&8[&e&lPots &b&lNetwork&8] &6[ID]&7: The real name of &3[PLAYER] &7is &e[NAME]&7.'
        Get Nicked Players Error: '&8[&e&lPots &b&lNetwork&8] &7At the moment no player is nicked.'
        Nicked Actionbar: '&eYou are nicked as &3[NAME]&e.'

Here is the plugins that I am using: Plugins (40): AsyncWorldEditInjector, MinecraftMarket, WorldEdit, Essentials, PlaceholderAPI, Craftconomy3, PlayerVisibilityReborn, ChatControl, PlugMan, NametagEdit, BetterNick, Votifier, WorldGuard, BetterNick-Addon, PotsLobby, AfkTp, VotingPlugin, AsyncWorldEdit, EssentialsProtect, EssentialsChat, EssentialsGeoIP, PermissionsEx, ReporterGUI, AACBungeeConnectSpigot, ViaVersion, Vault, EssentialsSpawn, CrazyCrates, ProtocolLib, LibsDisguises, SuperLobby, AAC, Citizens, eZProtector, ServerSigns, CommandNPC, SuperVanish, GadgetsMenu, AACAdditionPro, HolographicDisplays

**Comment by DomeDD** [comment]
Because you set an empty prefix in the config

**Comment by DomeDD** [comment]
Use '&r' as the new prefix if you don't want to use any color

**Comment by LoYungSum** [comment]
Thanks
