### ISSUE TITLE
Nicking does nothing

### ISSUE THREAD

**Issue by SoulWolfX** [DomeDD/BetterNick#31]
No matter what version the server runs when I nick nothing happens. here's an example
![2017-09-22_16 51 30](https://user-images.githubusercontent.com/30161396/30764091-72b5d8a0-9fb7-11e7-9496-cec4b363ea3c.png)
No errors appear in console

**Comment by LoYungSum** [comment]
It is because you are using luckyperms with bungeecord. As luckyperms bungee requires a bungee chat plugin to controls the chat and it will override the prefix by the server. And I think there is no way to fix it. (I think)

**Comment by SoulWolfX** [comment]
@LoYungSum no i am not using it on bungeemode lol

**Comment by DomeDD** [comment]
As already said in your last issue:
The error was caused by bad mysql connection (wrong mysql connection data)
And you said that you are running 1.7.10 - 1.12.1. But 1.7.10 is not supported which you can read here: https://www.spigotmc.org/resources/better-nick-api-1-8-3-1-12-2.39633/

**Comment by SoulWolfX** [comment]
@DomeDD so i cant use your plugin so i have to spend another month looking for a plugin

**Comment by DomeDD** [comment]
Or just remove 1.7.10 - 1.8.2 support. From 1.8.3 it will work fine!

**Comment by SoulWolfX** [comment]
But i need 1.7.10 without it ill be a bad server owner

**Comment by DomeDD** [comment]
But for me as the developer it is not possible to make a nick plugin possible which works with uuids and all the stuff from the 1.8 and above api

**Comment by SoulWolfX** [comment]
ill just use this other plugin i found thats popular
