### ISSUE TITLE
Skin will not change, /nicks or /nicklist is not working (comes up with error)

### ISSUE THREAD

**Issue by Shan12010MC** [DomeDD/BetterNick#33]
Hello!

When I do /nick or /skin it changes my name but does not change my skin, it says it does but as I said, it doesn't, it shows my skin is different in the tablist but when you go into F5 mode you have the same skin. Also /nicks and /nicklist comes up with a error. 

![2017-09-28_12 24 29](https://user-images.githubusercontent.com/25714451/30978278-175f181e-a448-11e7-8204-cc6a2d8bcc17.png)

Lastly, when I do /nick it changes my nick everywhere except my scoreboard. When I do /unnick it shows the nickname for like 5 seconds then goes back to normal.

Thanks, Shan

**Comment by DomeDD** [comment]
When you say you get an error, why you don't send the error code to me?
Scoreboard updates are not included in my plugin
