### ISSUE TITLE
CloudNet Support

### ISSUE THREAD

**Issue by BlockCraftMCPE** [DomeDD/BetterNick#35]
Hey! I'm using CloudNet Cloud System and the actual version of Your nick system dont work with it.It changes the name,but nametag and chattag dont change.Please add Support for CloudNet.
Regards,
BLOCKSTORM

**Comment by Felix5566** [comment]
CloudNet is very good i use it too, please add

**Comment by BlockCraftMCPE** [comment]
:)

**Comment by DomeDD** [comment]
A method to set a player a prefix in the cloudnet api does not exists at the moment. I'm in contact with the developer to add this asap

**Comment by BlockCraftMCPE** [comment]
Nice

**Comment by BlockCraftMCPE** [comment]
Thanks for fast support!
