### ISSUE TITLE
SRC

### ISSUE THREAD

**Issue by iTzGamer05** [DomeDD/BetterNick#36]
Hallo DomeDD und zwar habe ich mir vor kurzem ein SkyWarsSRC gekauft und beim joinen steht noch der echte nache da aber beim leaven dann der nickname was/wie muss ich in den SRC einfügen damit das geht? MFG Jonas

**Comment by Felix5566** [comment]
please wride english thanks :)

**Comment by Felix5566** [comment]
und zu deinem Beitarg dann musst du die API von den BetterNick in dieses SkyWarsSRC reinprogramieren oder den Dev der das programiert fragen ob er Support dafür hinzufügt :)
