### ISSUE TITLE
Unnick Fehler

### ISSUE THREAD

**Issue by Floxiii** [DomeDD/BetterNick#38]
Hey, wenn ich '/unnick' nutze kommt folgender Fehler:
https://hastebin.com/gunopihugo.vbs
mit folgender Kick Message:
https://files.floxiii.net/d/73s1472.png

**Comment by DomeDD** [comment]
Kommt der jedes mal? Weil soweit ich das sehen kann, liegt der Fehler in der CraftBukkit API
Aber ich werds bei mir auch mal testen

**Comment by Floxiii** [comment]
Ja kommt immer und jeder wird geklickt... Bis zum restart.

**Comment by DomeDD** [comment]
Nutzt du Spigot oder CraftBukkit?
