### ISSUE TITLE
Kann keine Nachricht schreiben.

### ISSUE THREAD

**Issue by DevFlare** [DomeDD/BetterNick#39]
Hey,

ich möchte, wie man merkt, einen Fehler melden. In der Lobby kann ich noch Nachrichten schreiben (funktioniert alles einwandfrei, außer der Name überm Spieler, da AnimatedNames installiert ist). Sobald ich dann mit Auto-Nick bzw. /nick einen anderen Unter-Server betrete, erhalte ich den Nick, etc. kann aber keine Nachrichten schreiben.

Meine Server haben Essentials installiert. Habe es auch ohne probiert, allerdings kann ich ebenfalls keine Nachrichten auf dem anderen Unter-Server schreiben.

Mit freundlichen Grüßen,
Flare

P.S. Und ja, ich habe um 03 Uhr Nachts nichts Besseres zu tun, als einen Error zu melden xD

**Comment by DomeDD** [comment]
Hallo. Mein Plugin hat gar nichts mit dem Minecraft Chat zu tun. Das muss dann wohl irgendeins der installierten Plugins zu tun.

**Comment by DevFlare** [comment]
Ja ich weiß. Aber wenn ich nicht genickt bin kann ich schreiben, wenn ich genickt bin allerdings nicht.. Wollte nur fragen ob du eventuell eine Antwort weißt. Werde mal nachsehen was das Problem sein könnte.

MfG,
Flare

**Comment by DevFlare** [comment]
Update: Andere sehen meine Nachrichten, ich selbst sehe diese aber nicht.

**Comment by DomeDD** [comment]
Welches Chat System nutzt du?

**Comment by DevFlare** [comment]
Wir nutzen Essentials. (In der Lobby nutzen wir auch Essentials, allerdings funktioniert dort der Chat. (Man kann Nachrichten schreiben, und man sieht diese auch)

**Comment by DomeDD** [comment]
Es kann sehr gut an Essentials liegen. Versuche es einmal ohne Essentials, ob du schreiben kannst und du deine Nachrichten lesen kannst

**Comment by DevFlare** [comment]
Habe ich bereits. Hat nichts geändert.
In unserer Lobby habe ich ja auch Essentials installiert, und da funktioniert es.

**Comment by DomeDD** [comment]
Das ist komisch. Es muss an irgendeiner Einstellung von Essentials oder einem anderen Plugin liegen, denn meins hat rein gar nichts mit dem PlayerChatEvent in Minecraft zu tun ;)

**Comment by DevFlare** [comment]
Mh. Keine Ahnung. Ich werde mal sehen was ich machen kann. Essentials kann ich nicht entfernen, da es viele Befehle, etc. enthält die wir nutzen. Haben zwar auch CMI aber einige unserer Plugins nutzen das Economy System von Essentials.
