### ISSUE TITLE
error occurred while attempting to perform /skin in 1.12

### ISSUE THREAD

**Issue by DanyardTheWolf** [DomeDD/BetterNick#4]
Idk why it does that

**Comment by DomeDD** [comment]
Did you perform /skin or /skin <name>. If the name is not a valid player, the error occures

**Comment by DanyardTheWolf** [comment]
/skin name and i get the error message right under &8[&5Nick&8] &7Your nickname is &5[NAME]&7 after ive done /nick

**Comment by DomeDD** [comment]
Ok, do I understand that right? At first you nick, you got a new name and a skin. After that you perform /skin <name> and you get an error? Try to use an valid name. I'm trying to fix that asap.

**Comment by DanyardTheWolf** [comment]
I just did like /nick TheQuackKing and it changed the nick but when it was about to change to a random skin it kicked all of the players.
