### ISSUE TITLE
Whats the Problem ???

### ISSUE THREAD

**Issue by Newspicel** [DomeDD/BetterNick#40]
I make that class from a Plugin and the Plugin don't make what... Here the class from my plugin who i make with Better nick https://hastebin.com/jogugubupu.java sorry for my english problem i'am german guy.

**Comment by Newspicel** [comment]
My problem is with the api

**Comment by Newspicel** [comment]
thats my consloe https://hastebin.com/pepuripufi.go

**Comment by DomeDD** [comment]
Please read the API documentation before trying to implement the API (https://github.com/DomeDD/BetterNick/blob/master/NickedPlayer.java)

The constructor "NickedPlayer(Player player)" requires a player as first param
