### ISSUE TITLE
NameTag bug

### ISSUE THREAD

**Issue by LoYungSum** [DomeDD/BetterNick#41]
![image](https://user-images.githubusercontent.com/25066078/33123557-8194c326-cfb5-11e7-804c-7f16545c7c02.png)

Settigns here:
Config:
    Auto Update Check: true
    Auto Update Download: false
    API Mode: false
    Use Vault: false
    # If true, you won't get a nickname on join (if the client enabled AutoJoin and has the Permissions)
    Lobby Mode: false
    # Nick Name Prefix for chat messages; I recommend to leave Display Name Prefix empty
    Display Name Prefix: '&7'
    # Nick Name Prefix for nametag; I recommend to leave Name Tag Prefix empty if you didn't install NametagEdit
    Name Tag Prefix: '&7'
    # Nick Name Prefix for tablist
    Tablist Name Prefix: '&7'
    # Overwrites the Player Prefix, on unnick the Player will get his old Prefix (if "Config.Use Vault" == true)
    Permissions System Player Prefix: ''
    # Be aware of that the Client gets killed and respawned when Skin Self Update is true
    Skin Self Update: false
    Nicked Actionbar: true

**Comment by LoYungSum** [comment]
Nametag is not &7

**Comment by DomeDD** [comment]
Did you install NTE and is it enabled?

**Comment by LoYungSum** [comment]
Yes

**Comment by DomeDD** [comment]
Interesting... looking for a fix
