### ISSUE TITLE
Vault support

### ISSUE THREAD

**Issue by LoYungSum** [DomeDD/BetterNick#42]
When I enable the vault support and type /unnick, it will generate this error

22.11 18:39:49 [Server] INFO SunnyLo issued server command: /nick
22.11 18:39:51 [Server] INFO l0L_G4M3r issued server command: /unnick
22.11 18:39:51 [Server] ERROR null
22.11 18:39:51 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'unnick' in plugin BetterNick v5.1
22.11 18:39:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
22.11 18:39:51 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
22.11 18:39:51 [Server] INFO Caused by: java.lang.NullPointerException: prefix
22.11 18:39:51 [Server] INFO at me.lucko.luckperms.bukkit.vault.VaultChatHook.setPlayerPrefix(VaultChatHook.java:93) ~[?:?]
22.11 18:39:51 [Server] INFO at net.milkbowl.vault.chat.Chat.setPlayerPrefix(Chat.java:114) ~[?:?]
22.11 18:39:51 [Server] INFO at de.domedd.betternick.packets.v1_8_R3.unNick(v1_8_R3.java:223) ~[?:?]
22.11 18:39:51 [Server] INFO at de.domedd.betternick.api.nickedplayer.NickedPlayer.unNick(NickedPlayer.java:251) ~[?:?]
22.11 18:39:51 [Server] INFO at de.domedd.betternick.commands.UnNickCMD.onCommand(UnNickCMD.java:32) ~[?:?]
22.11 18:39:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
22.11 18:39:51 [Server] INFO ... 15 more

**Comment by DomeDD** [comment]
Do you have Vault and a Vault compatible Chat plugin installed?

**Comment by LoYungSum** [comment]
Vault version 1.6.1
Vault chat plugin: ChatControl

**Comment by DomeDD** [comment]
All plugins on newest version?

**Comment by LoYungSum** [comment]
wait, I think an admin remove ChatControl, let me install it back and test it if it still occurs.
