### ISSUE TITLE
Issue and Suggestion

### ISSUE THREAD

**Issue by Somuone** [DomeDD/BetterNick#43]
An issue I've found with this plugin (using Spigot 1.8.8) is **"An internal error occurred while attempting to perform this command"** when I type the '/unnick' command sometimes the '/nick' command. I'm using MySQL.

A suggestion I have is an option in the config to make the nicked player the skin of the person they've nicked as.

**Comment by DomeDD** [comment]
If you say you get an error, why you don't send it to me?
Your suggestion is not possible because the nicknames are fantasy names. They don't exists as a mojang account where I can get a skin from
