### ISSUE TITLE
Everyone gets kicked when i try to nick myself as a specific person.

### ISSUE THREAD

**Issue by DanyardTheWolf** [DomeDD/BetterNick#45]
![screenshot 16](https://user-images.githubusercontent.com/29733625/33605772-5c8d9692-d9bb-11e7-90d9-c718f09fefea.png)

**Comment by DomeDD** [comment]
Did you set a Name Tag Prefix in the config.yml and you don't use NTE? If yes, that's the reason. The Name Tag prefix can be 2 chars long if you don't use NTE

**Comment by DanyardTheWolf** [comment]
I dont use NTE, and the name tag prefix is empty.

**Comment by DanyardTheWolf** [comment]
Its still kicking all players
