### ISSUE TITLE
Nick System funktioniert nicht mehr | Nick system does not work

### ISSUE THREAD

**Issue by marrobHD** [DomeDD/BetterNick#46]
Hallo DomeDD, seit dem neuen Nicksystem update werden keine Daten an die Mysql datenbank geschrieben. Außerdem funktioniert autonick nicht mehr. 

Hello DomeDD, since the new Nicksystem Update no data is written to the Mysql database. Exceptionally autonick does not work anymore.

**Comment by DomeDD** [comment]
Did you add this to your config.yml? https://pastebin.com/7shPHQsk

**Comment by marrobHD** [comment]
Yes, i have this added. And i have try delete the config and generate a new. that did not work either.

**Comment by DomeDD** [comment]
Please delete the BetterNick.jar and the BetterNick folder and reinstall the plugin
