### ISSUE TITLE
/msg bug

### ISSUE THREAD

**Issue by Unsalt** [DomeDD/BetterNick#47]
Hi there, this is an amazing plugin. However, I found a bug that will expose nicked players. For example, my ign is "Unsalt", and when I autonick to a random name, let's say "DomeDD", players can still /msg DomeDD (this means that the plugin is working fine). However, players can also /msg Unsalt which is extremely bad because they will know "DomeDD" is "Unsalt". Please fix this so when players do /msg Unsalt it will say "Error: Player not found". Thanks.

**Comment by DomeDD** [comment]
I will take a look at it and fix it asap!

**Comment by Techno3600** [comment]
Maybe to fix it you DomeDD could make it so the tabbed name internally  forwards to the real name of the player.

**Comment by DomeDD** [comment]
You have to use a custom /msg plugin
