### ISSUE TITLE
Skin and Essentials BUG

### ISSUE THREAD

**Issue by SpooderCraft** [DomeDD/BetterNick#50]
#Please Fix the skin it will not change the player skin. AND. please fix it so it works with #Essentials change-displayname!!!! PLZ!

**Comment by SpooderCraft** [comment]
and work with coloredtags

**Comment by DomeDD** [comment]
It changes the player skin. If you want to see your own new skin you have to enable Skin Self Update int the config.yml

**Comment by SpooderCraft** [comment]
We do it does not change it. And can u make it so it changes the prefix??

**Comment by Techno3600** [comment]
You can change the prefix in the configuration, also, it requires vault to actually change the prefix/displayname across the server.
