### ISSUE TITLE
Find a Better Way to /skin

### ISSUE THREAD

**Issue by Techno3600** [DomeDD/BetterNick#51]
Hi!

I really like this plugin and everything is awesome about it, the only thing that I don't like is while almost everything is flawless in the code, the /skin is so buggy and I don't think that killing the player should be necessary to refresh the skin, I found [this plugin](https://github.com/games647/ChangeSkin) maybe you could check how they code it, in this plugin they do not kill the player, the skin just refreshes. Also, [this error](https://pastebin.com/HsZZsmua) stops any players from un-nicking. Lastly in the latest code when /skin (or when the skin updates), it puts the player into Spectator Mode.

I hope this helps, this plugin has a lot of potential and I look forward to seeing future updates.

Thanks
Techno

**Comment by DomeDD** [comment]
Coming in the next update!
