### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by jason19148** [DomeDD/BetterNick#54]
When I have a nick on and I type in chat, it shows my regular username instead of my nicked username. 
![2018-01-01_07 58 33](https://user-images.githubusercontent.com/35004432/34468998-c697d764-eec9-11e7-8171-60d8c0bbedc2.png)

**Comment by DomeDD** [comment]
You have to change that in your chat plugin. Use the displayname instead of the regular name. Or if it is a self-made hat plugin use my api.
