### ISSUE TITLE
the plugin isn't even running anymore?. [IM NEW NO JUDGE]

### ISSUE THREAD

**Issue by Etqrnal** [DomeDD/BetterNick#56]
ok so im new with the plugin (i just installed it)

and my issue is that i can nick and all, but after i nick, all the commands on the server are useless.. nothing works i do /nick, then i write /unnick, doesnt work... then i write /nick reload.. doesnt work.. nothing works after i do /nick

there are my settings (config.yml)

Config:
    Auto Update Check: true
    Auto Update Download: true
    API Mode: false
    Use Vault: false
    # If true, you won't get a nickname on join (if the client enabled AutoJoin and has the Permissions)
    Lobby Mode: false
    # Nick Name Prefix for chat messages; I recommend to leave Display Name Prefix empty
    Display Name Prefix: ''
    # Nick Name Prefix for nametag; I recommend to leave Name Tag Prefix empty if you didn't install NametagEdit
    Name Tag Prefix: ''
    # Nick Name Prefix for tablist
    Tablist Name Prefix: '&8Player &e| &7'
    # Overwrites the Player Prefix, on unnick the Player will get his old Prefix (if "Config.Use Vault" == true)
    Permissions System Player Prefix: '&8Player &e| &7'
    # Be aware of that the Client gets killed and respawned when Skin Self Update is true
    Skin Self Update: false
    Nicked Actionbar: true
    Keep NickName On Quit: false

i dont have any plugins that are on the list of "incompatible plugins" and im on the normal spigot server that runs on 1.8.3 to the latest version cuz of ViaVersion please help me

**Comment by DomeDD** [comment]
Interesting. Can you send me a list of your installed plugins?

**Comment by Etqrnal** [comment]
yes, i could give you a list of plugins..

Plugin List:
BetterNick
ChatManagement
ChestCommands
CommandNPC
CustomJoinItems
Duels
FastAsyncWorldEdit
GadgetsMenu
HideandCustomPlugins
HolographicsDisplays
HubThat
Multiverse-Core
PAC (AntiCheat Plugin - Phoenix Anti Cheat)
PerWorldChatPlus
PerWorldInventory
PerWorldPlugins
PermissionsEX
PlaceHolderAPI
PluginMetrics
ProScoreBoard
ProtocolLib
Tablist
Trollboss
UltraVanish
Updater
Vault
ViaVersion
VoidSpawn
VoidWorld
bstats
WorldGuard
(a jar file called Worldedit-Bukkit5.1.3.jar), i dont know if FAWE needs world edit to run so i installed that

hopefully this helps

**Comment by Etqrnal** [comment]
i updated my plugin list.. this time i just put it in a screenshot because i believe its a bit easier to see
link: http://i.imgur.com/yvOD6mj.png

**Comment by DomeDD** [comment]
Okay, can you start a server only with BetterNick installed? If that works, you can add the plugins one by one and test if BetterNick is working. When it stops working you know that the last installed plugin is causing that issue

**Comment by Etqrnal** [comment]
i personally feel like the plugin is interfering with other Chat Plugins installed for eg
PerWorldChatPlus
ChatManagement
maybe a problem with PermissionsEX?

After Test:

The Plugin im using on is on spigot 1.8.3 now, the plugin stays to not work yet the Folder showed up as  
normal but the plugin isnt showing any signs of life, im also opped and still... nothing.. i did /help betternick and that works but the plugin is dead for me.... i dont understand this

**Comment by Etqrnal** [comment]
i will update when it works

**Comment by DomeDD** [comment]
My plugin doesnt change anything at the chat format and performs perfectly with pex. And 1.8.3 should work. Do you get any messages in the console like this from BetterNick? "Minecraft version v1_8_R1 is not supported"
