### ISSUE TITLE
Chat + Commands Not working whilst nicked

### ISSUE THREAD

**Issue by CubiMCServer** [DomeDD/BetterNick#58]
Hi there! I am currently using BetterNick on my server. When i type /nick it works perfectly fine and gives me a nickname etc. But when i try to say something in chat it doesn't appear and when i do commands they don't execute? I do have Essentials but BetterNick DID work with essentials before!?
Plugins: https://imgur.com/kG3Raud

**Comment by DomeDD** [comment]
Did you try an older version of BetterNick? Or did you install any other new plugin when BetterNick stoped working properly?

**Comment by CubiMCServer** [comment]
I installed perworldchat and perworldtablist

**Comment by DomeDD** [comment]
Maybe it's one of these plugins...?
