### ISSUE TITLE
/nick [nickname]

### ISSUE THREAD

**Issue by jason19148** [DomeDD/BetterNick#60]
When I do /nick [nickname], (NOT just /nick) it kicks me out of the server instead of giving me that nickname.

**Comment by DomeDD** [comment]
Which message do you get when you get kicked? Is the name longer than 14 letters?

**Comment by jason19148** [comment]
I forgot what message I got, but I nicked myself random names such as "noob".

**Comment by DomeDD** [comment]
Does that still happen?

**Comment by jason19148** [comment]
Idk I can't check right now. I am running minecraft bungeecord 1.12 with three servers: lobby, sky block, factions. (I only have the plugin on my lobby server for now.)

**Comment by jason19148** [comment]
My username is jasonplayszYT. I gave myself the owner rank on my server. Maybe the additional owner rank is why that happens?

**Comment by DomeDD** [comment]
Dont think so...

**Comment by jason19148** [comment]
It works now!
