### ISSUE TITLE
Error when typing /nicks

### ISSUE THREAD

**Issue by LoYungSum** [DomeDD/BetterNick#61]
![image](https://user-images.githubusercontent.com/25066078/35035015-fa188c44-fbaa-11e7-8467-57c88e6448c6.png)

What version of vault, nametagedit and essentialschat should I use?

**Comment by DomeDD** [comment]
The newest one?

**Comment by LoYungSum** [comment]
You should have no errors when type /nicks, so what pl do you have and what version is it?

**Comment by DomeDD** [comment]
PermissionsEx: 1.23.4
NametagEdit: 4.2.0
DeveloperAPI: 1.4
Vault: 1.6.1
BetterNick: 5.6
ChatEx: 1.6

**Comment by LoYungSum** [comment]
Maybe I have found the problem. When I use the default config, there are no errors, but when I use this config, there will be an error, try using this config and see if there is an error.

Config:
    Auto Update Check: true
    Auto Update Download: true
    API Mode: false
    Use Vault: true
    # If true, you won't get a nickname on join (if the client enabled AutoJoin and has the Permissions)
    Lobby Mode: false
    # Nick Name Prefix for chat messages; I recommend to leave Display Name Prefix empty
    Display Name Prefix: '&7'
    # Nick Name Prefix for nametag; I recommend to leave Name Tag Prefix empty if you didn't install NametagEdit
    Name Tag Prefix: '&7'
    # Nick Name Prefix for tablist
    Tablist Name Prefix: '&7'
    # Overwrites the Player Prefix, on unnick the Player will get his old Prefix (if "Config.Use Vault" == true)
    Permissions System Player Prefix: '&7'
    # Be aware of that the Client gets killed and respawned when Skin Self Update is true
    Skin Self Update: false
    Nicked Actionbar: true
    Keep NickName On Quit: false

**Comment by DomeDD** [comment]
Working on a fix!

**Comment by DomeDD** [comment]
Update is out!
