### ISSUE TITLE
Actionbar-Delay

### ISSUE THREAD

**Issue by Xge21** [DomeDD/BetterNick#63]
In der Actionbar nur für ein paar Sekunden anzeigen, dass man als wer auch immer genickt ist. Auf dauer nervt die Actionbar nämlich.

**Comment by DomeDD** [comment]
Dann musst du die Actionbar deaktivieren, wenn sie dich nervt ;)

**Comment by Xge21** [comment]
Na ja, aber es ist glaube ich trotzdem gut, dass man einstellen kann, ob die Actionbar permanent oder nur für ein paar Sekunden eingeblendet wird. Es gibt viele andere Plugins, die das als Hauptkommunikationsmittel benutzen.
