### ISSUE TITLE
New feature  // Support for NametagEdit

### ISSUE THREAD

**Issue by Xge21** [DomeDD/BetterNick#7]
Da die meisten Nutzer ein ColoredTablist-Plugin benutzen, und NametagEdit das meist genutzte ist, würde ich mir gerne wünschen, dass NametagEDIT unterstützt wird :D // [ https://www.spigotmc.org/resources/nametagedit.3836/ ]

LG

**Comment by DomeDD** [comment]
Was funktioniert denn nicht, bzw. was soll genau aus Nametagedit unterstützt werden?

**Comment by Xge21** [comment]
Im Tab hat man immer noch den gleichen Tag, wegen der Permission.

**Comment by DomeDD** [comment]
Werde ich mir nach meinem Urlaub angucken.

**Comment by 8Marc8** [comment]
#push

**Comment by DomeDD** [comment]
NametagEdit support will be added in the next update
