### ISSUE TITLE
Chat Prefix not Changing(Bug)

### ISSUE THREAD

**Issue by macluxHD** [DomeDD/BetterNick#70]
If I nick myself the Chat prefix isn't changing (I'm using permissionsex.)

**Comment by rh-programm** [comment]
Yes, I have the same problem ...

**Comment by DomeDD** [comment]
Do you mean the !Persmissions System Player Prefix" or the "Display Name Prefix"?

**Comment by kxii** [comment]
[https://imgur.com/uWx733L](url) When you go back to your normal name, the prefix doesn't change...

**Comment by kxii** [comment]
FIX:
You must go into your Permissions.yml and find your username, it will have the broken prefix in each world, you'll need to remove it.
![image](https://user-images.githubusercontent.com/37308266/37303325-0a4dd6aa-2626-11e8-8338-b8c4af56601f.png)

**Comment by DomeDD** [comment]
That has been fixed!
