### ISSUE TITLE
[Feature Request] Join Message

### ISSUE THREAD

**Issue by rh-programm** [DomeDD/BetterNick#73]
Hallo,
Ist es möglich, die Join-Nachricht zu ändern, wenn ich genickt bin?

**Comment by DomeDD** [comment]
Das kannst du mit plugins machen, die die join nachricht ändern. Mein Nick plugin ist nicht gemacht um irgendwelche chat nachrichten zu ändern ;)

**Comment by rh-programm** [comment]
Ja ist schon klar, nur es geht darum, dass wenn ich genickt bin bzw. wenn `Keep NickName On Quit:` auf `true` ist, wird beim Joinen mein richtiger Player Name angezeigt und nicht der Nickname.
