### ISSUE TITLE
[BUG] Nickname Konflikte

### ISSUE THREAD

**Issue by hampoelz** [DomeDD/BetterNick#74]
Hallo, Wenn ich genickt bin, benutzen andere Plugins meinen Nicknamen statt meinem "Richtigen" Player Namen. Ist an sich ganz gut, wegen der der 'Tab' Funktion im Chat ...
Das Problem ist aber dass z.b mein Vault Kontostand, wenn ich genickt bin auf `0 Coins` ist, statt meinem eigentlichen Kontostand. Wenn ich mich wieder Entnicke habe ich wieder meinen eigentlichen Kontostand. Bei Citybuild (`PlotSquared`) oder bei Skyblock (`uSkyBlock`) ist dasselbe Problem nur eben mit Plots und Inseln.

**Comment by DomeDD** [comment]
Ich gehe mal davon aus, dass du iConomy benutzt, da iConomy deine Coins deinem Namen zuordnet und nicht deiner UUID. Ich werde, sobald ich Zeit dafür habe, nach einer Möglichkeit suchen, iConomy zu unterstützen!

**Comment by rh-programm** [comment]
Ja stimmt ich benutze iConomy ...
Das Problem besteht aber auch bei uSkyBlock

**Comment by DomeDD** [comment]
Wird einer Insel eine UUID bzw der UUID eine Insel zugeordnet oder wird anstatt der UUID der Name des Spielers benutzt?

**Comment by rh-programm** [comment]
Hab mich ein bisschen im Plugin Ordner Umgesehen ... es wird überall UUID und Spieler Name gespeichert.

**Comment by hampoelz** [comment]
Benutze jetzt aSkyblock, da uSkyblock sowieso nicht mehr geupdatet wird.
Bei aSkyblock funktioniert alles einwandfrei.
