### ISSUE TITLE
[Feature Request] Keep Skin on quit

### ISSUE THREAD

**Issue by rh-programm** [DomeDD/BetterNick#75]
Hallo,
Kannst du eine Option machen, um die Skin beim Verlassen des Servers zu behalten, wie die Funktion `Keep NickName On Quit`, aber mit Skins?

**Comment by DomeDD** [comment]
Nicht möglich, weil ich einem Spieler nur temporär einen neuen Skin setzen kann.

**Comment by rh-programm** [comment]
Doch es sollte gehen ...
In der Config ist ja eine liste der ganzen Skins, von der ein Random Skin genommen wird - du könntest den `String` der bei der Random Skin Auswahl raus kommt in z.b. der Datei `NickedPlayers.yml` speichern und dem Player beim Joinen den Skin wieder zuweisen?
