### ISSUE TITLE
Nick prefix

### ISSUE THREAD

**Issue by LoYungSum** [DomeDD/BetterNick#85]
Prefix not replacing.

Plugins: BowHealth, CleanroomGenerator, LuckPerms, ArrowTrails, PlaceholderAPI, PlugMan, NametagEdit, PotsPVP, BuycraftX, VoidSpawn, Multiverse-Core, FastAsyncWorldEdit, NoFall, NetworkLevels, PotsReport, Vault, ProtocolSupport, PearlFix, WorldEdit, FBasics, Essentials, BetterNick, WorldGuard, Citizens, DiscordSRV, EssentialsProtect, EssentialsGeoIP, EssentialsChat, ReporterGUI, EssentialsAntiBuild, ViaVersion, EssentialsSpawn, StrikePractice, ProtocolLib, Spartan, eZProtector, React, PremiumVanish, HolographicDisplays

![image](https://user-images.githubusercontent.com/25066078/37384482-2869d25a-278a-11e8-9790-f1d4db44d422.png)
![image](https://user-images.githubusercontent.com/25066078/37384485-31846b20-278a-11e8-99d4-7897a89fa35a.png)

**Comment by DomeDD** [comment]
Should be fixed in version 6.5
