### ISSUE TITLE
When doing /nick completely erases the nick 

### ISSUE THREAD

**Issue by Bumblebee309** [DomeDD/BetterNick#87]
So I own a network with a few other people and we decided to test it out so when we installed it and I did /nick the name got erased in the chat and scoreboard 
![image](https://user-images.githubusercontent.com/32628438/38070158-0aba2eba-32e0-11e8-8ebd-8870827e8a87.png)

**Comment by DomeDD** [comment]
Which Scoreboard and Chat plugin do you use? But the tablist name is correct?

**Comment by Bumblebee309** [comment]
1. Quickboard 
2.I use Pex
3. Yes the name in the tab is correct

**Comment by DomeDD** [comment]
Could you send me your server ip that I could see it?

**Comment by Bumblebee309** [comment]
play.centmc.tk

**Comment by Tiago1098** [comment]
Happens to me too

**Comment by DomeDD** [comment]
This has been fixed!
