### ISSUE TITLE
Essentials and maybe other plugins

### ISSUE THREAD

**Issue by Fernthedev** [DomeDD/BetterNick#89]
So I've used this plugin in the past, didn't work correctly but I think it did change the name at least. But then I tried it again and it was working without errors until I noticed... It wasn't even changing the name in either chat or nametag. I do use NameTagEdit and it is supposedly supported unless Essentials has something to do with /nick or something but it hasn't changed my nametag. In chat, it removes my prefix but I keep my nick which I'm assuming is something essentials done.Also when unnicked the suffix disappears and I have to reset it to appear. If you need a complete list of plugins I will send it. I also have it on MySQL and the lobby in lobby mode(Unless the lobby addon jar still exists and I can't find it). Is there something I have to do to fix these issues or something I have to wait for if possible?

**Comment by Fernthedev** [comment]
Well thing is I use luckperms and vault, but when the player nicks the prefix is set to the group's prefix, not the player's, and the suffix get's removed. On unnick it stays the same, but the nick does work with chat if you don't have an essentials nick, but the nametag didn't change at all. I'm just wondering why unless it's something with LuckPerm's compability with vault, because I've updated LuckPerms to the latest version and still happens.

**Comment by DomeDD** [comment]
The support for LuckPerms was fixed in version 6.5. Essentials support will come soon
