### ISSUE TITLE
AutoNick Item

### ISSUE THREAD

**Issue by DekoLP** [DomeDD/BetterNick#9]
Hey,

ich habe das Problem dass ich nicht das AutoNick Item bekomme. Es kommen keine Fehler in der Console 
Außerdem kann man sich taben

LG
DekoLP

**Comment by DomeDD** [comment]
Ist das LobbyAddon auf dem Server installiert? 
Hat der Spieler die benötigte Berechtigung, das Item zu bekommen? (BetterNick.JoinItem)

Das man den Spieler noch tabben kann, ist richtig so. Sonst wäre es zu auffällig, dass man andere Spieler tabben kann, aber genickte nicht ;)

**Comment by DekoLP** [comment]
Ist das LobbyAddon auf dem Server installiert?
Hat der Spieler die benötigte Berechtigung, das Item zu bekommen? (BetterNick.JoinItem)
Ja

Das man den Spieler noch tabben kann, ist richtig so. Sonst wäre es zu auffällig, dass man andere Spieler tabben kann, aber genickte nicht ;)

Man kann ja genickte Tabben und dann sieht man die echten Namen

**Comment by DomeDD** [comment]
Liegt eventuell ein anderes Item auf dem Slot für das Nicktool, z.b. von einem Lobby Plugin oder so?

**Comment by DomeDD** [comment]
Man kann ja genickte Tabben und dann sieht man die echten Namen

In der 1.12 geht es mit dem genickten Namen. 1.8.4 - 1.8.8 probiere ich gleich mal aus

**Comment by DekoLP** [comment]
Liegt eventuell ein anderes Item auf dem Slot für das Nicktool, z.b. von einem Lobby Plugin oder so?

Nein mit einem Gadgets Plugin plus Lobby Plugin gehts

Alles andere auch. Nur das Nickplugin geht nicht

**Comment by DomeDD** [comment]
Sind beide Plugins (BetterNick & BetterNick [LobbyAddon]) aktiviert?

**Comment by DekoLP** [comment]
ja

**Comment by DomeDD** [comment]
Kannst du mir einen Pastebin (https://pastebin.com/) mit deiner latest.log schicken?

**Comment by DekoLP** [comment]
https://hastebin.com/ufizubepaj.sql

**Comment by DekoLP** [comment]
Du kannst auf den Server
