### ISSUE TITLE
Nick doesn't work in chat. 

### ISSUE THREAD

**Issue by FreezerMoosh** [DomeDD/BetterNick#90]
/Nick works perfectly! BUT! in chat, only the essentials prefix comes up! also, i don't want the prefix to come up, just be default rank. FOr example = First Name: [DEV]Defectiveness -- Nickname: RandomNick

**Comment by DomeDD** [comment]
If you would have read the whole plugin overview you would know that Essentials Chat is not yet supported!
Support for essentials will come in the next update!
