### ISSUE TITLE
Economy problem

### ISSUE THREAD

**Issue by masterhacka** [DomeDD/BetterNick#93]
I am using Essentials for economy on my Bungeecord server network. For Eco sync I am using MySqlEcoSync. When I switch nick names I can increase my money. I hope there will be a fix for that.

**Comment by DomeDD** [comment]
I developed the Eco support of Essentials only for single servers. But I'm looking for an update for MySqlEcoSync

**Comment by masterhacka** [comment]
I hope this update will come soon.
