### ISSUE TITLE
Hilfe bei der BetterNickAPI benötigt!!!

### ISSUE THREAD

**Issue by Justxn01** [DomeDD/BetterNick#96]
Bitte angucken und mir sagen, woran es liegt/liegen kann.

https://hastebin.com/isorawojop.go

https://hastebin.com/eniqegekaq.java

https://hastebin.com/ilocucofow.java

**Comment by Justxn01** [comment]
Bei Link 1 sollte man mein Problem sehen.

**Comment by Justxn01** [comment]
Ich benutze die neuste Version der BetterNickAPI und außerdem benutze ich auch CloudNet.

**Comment by DomeDD** [comment]
Warum genau der Fehler entsteht, kann ich dir grade nicht sagen. Aber wenn du CloudNet benutzt kannst du setPlayerTablistName weg lassen

**Comment by Justxn01** [comment]
Danke ;)

**Comment by Justxn01** [comment]
Vllt. liegt es ja an der CloudNetAPI...
Kannst du oder kann mir jemand die aktuellste Version der CloudNetAPI bitte schicken?

**Comment by Justxn01** [comment]
Ich wäre sehr dankbar, für eine Lösung des Problems.

**Comment by DomeDD** [comment]
https://pastebin.com/kAPXdPjN
Ich habe den Code mal etwas überarbeitet. Ich hoffe du findest dadurch. Du hast die Klasse NickCommand nicht richtig instanziiert

**Comment by Justxn01** [comment]
Ich habe es zwar noch nicht getestet, aber bedanke mich trotzdem schonmal für deine Hilfe.

**Comment by Justxn01** [comment]
Es geht irgendwie immer noch nicht :/

Können mir eventuell Morgen mal reden, sodass du mir dann helfen kannst?

**Comment by Justxn01** [comment]
?

**Comment by Justxn01** [comment]
...

**Comment by DomeDD** [comment]
Adde mich auf Skype: live:dominik.diller_1

**Comment by Justxn01** [comment]
Sry, habe es jetzt erst gelesen..

**Comment by Justxn01** [comment]
https://hastebin.com/yitakaqaju.java

Wenn ich /msg <Spieler> <Nachricht> mache:
z.B. : /msg <Spieler> Hallo :#
dann wird die Nachricht verdreht.
Die neue Nachticht ist/wäre dann: :# Hallo

**Comment by Justxn01** [comment]
Kann mir bitte jemand helfen?

**Comment by DomeDD** [comment]
https://pastebin.com/sg5MehEe
