### ISSUE TITLE
Betternick Problem mit Mysql und nicken

### ISSUE THREAD

**Issue by Spark61** [DomeDD/BetterNick#99]
Hallo, 
ich habe ein Problem, wenn ich mich / Nick habe ich einen anderen Skin und in Tab einen anderen Namen aber wenn ich jemand anderen Anschaut ist als Name immer nur ein Leerzeichen. Zweiteres Problem, wenn ich mit meinem MySQL-Server zusammen bin, dann ist es ein Problem das es auch beim Nicken steht? Danke im Vorraus.

LG Spark61

**Comment by DomeDD** [comment]
Wurde in v7.0 gefixt!
